server:
  port: 8888

spring:
  application:
    name: api-gateway
  profiles:
    include:
      - gateway-default-filters
      - routes
      - logging
#      - endpoints
      - metrics
      - otlp
      - google