spring:
  cloud:
    gateway:
      routes:
        - id: query
          uri: https://httpbin.dmuth.org
          predicates:
            - Method=GET
            - Path=/apis/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # This is the rate at which the token bucket is filled.
                redis-rate-limiter.replenishRate: 1
                # This is the maximum number of requests a user is allowed in a single second
                # & the number of tokens that the buketOfToken can hold.
                redis-rate-limiter.burstCapacity: 60
                # This is the number of tokens taken from the bucket for each request.
                redis-rate-limiter.requestedTokens: 10
                # see: configs/RateLimiter
                key-resolver: "#{@rateLimiterIdentifier}"

        - id: command
          uri: https://httpbin.dmuth.org
          predicates:
            # IP WHITELISTING
#            - XForwardedRemoteAddr=192.168.1.1/32
            - Method=POST
            - Path=/apis/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 10
                key-resolver: "#{@rateLimiterIdentifier}"