management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - loggers
#          - gateway

  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      enabled: true
#    gateway:
#      enabled: true # default value

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
          client:
            request: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0